
package View.GiaoDienChinh.JPanel;

import Controller.ConnectionMySQL_SanPhamDaBan;
import java.util.ArrayList;
import Model.BanHangCode;

/**
 *
 * @author Admin
 */
public class HoaDonDonHangJPanel extends javax.swing.JPanel {

    ArrayList<BanHangCode> list;
    static int soLanBan = 1;
    public HoaDonDonHangJPanel() {
        initComponents();
        list = new ConnectionMySQL_SanPhamDaBan().getListThongTinDonHangBan();
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabelAnhSP = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelSoLuongBan = new javax.swing.JLabel();
        jLabelThanhTien = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelMaMatHang = new javax.swing.JLabel();
        jLabelLoaiHang = new javax.swing.JLabel();
        jLabelGiaBan = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/DonHang/nen.jpg"))); // NOI18N

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAnhSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAnhSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/DonHang/donhang.png"))); // NOI18N
        jLabelAnhSP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabelAnhSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 90, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Thành tiền : ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, -1, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Loại hàng : ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 100, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Mã mặt hàng : ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 130, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Số lượng bán : ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 130, 30));

        jLabelSoLuongBan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelSoLuongBan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSoLuongBan.setText("5");
        jLabelSoLuongBan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabelSoLuongBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 40, 30));

        jLabelThanhTien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelThanhTien.setForeground(new java.awt.Color(0, 0, 255));
        jLabelThanhTien.setText("1,000,000 VNĐ");
        add(jLabelThanhTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 160, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Giá bán      : ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 120, 30));

        jLabelMaMatHang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelMaMatHang.setText("AKJ5");
        add(jLabelMaMatHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 70, 30));

        jLabelLoaiHang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelLoaiHang.setText("Áo khoát Jean");
        add(jLabelLoaiHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 150, 30));

        jLabelGiaBan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelGiaBan.setText("1000000");
        add(jLabelGiaBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 180, 30));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOpaque(true);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 800, 10));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/NhapKho/nenNhapKho.jpg"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 120));

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents
 
    long ChuyenChuoiThanhSo(String n){
        char[] ch = n.toCharArray();
        String s = "";
        for(int i=0;i<ch.length;i++){
            if(ch[i]>=48 && ch[i]<=57){
                s += ch[i];
            }     
        }
        long num = Long.parseLong(s);
        return num ;
    }   
    String XuLiSo(long n){
        String a = "" , b = null;
        a = String.valueOf(n);
        switch(a.length()){
            case 1:
            case 2:
            case 3:
                b = a;
                break;
            case 4:
                b = a.substring(0,1)+","+a.substring(1,4);
                break;
            case 5:
                b = a.substring(0,2)+","+a.substring(2,5);
                break;
            case 6:
                b = a.substring(0,3)+","+a.substring(3,6);
                break;
            case 7:
                b = a.substring(0,1)+","+a.substring(1,4)+","+a.substring(4,7);
                break;
            case 8:
                b = a.substring(0,2)+","+a.substring(2,5)+","+a.substring(5,8);
                break;
            case 9:
                b = a.substring(0,3)+","+a.substring(3,6)+","+a.substring(6,9);
                break;
            case 10:
                b = a.substring(0,1)+","+a.substring(1,4)+","+a.substring(4,7)+","+a.substring(7,10);
                break;
            case 11:
                b = a.substring(0,2)+","+a.substring(2,5)+","+a.substring(5,8)+","+a.substring(8,11);
                break;
            case 12:
                b = a.substring(0,3)+","+a.substring(3,6)+","+a.substring(6,9)+","+a.substring(9,12);
                break;
        }
        return b  ;
    }     
    int XetSoLanBan(){
        int max = 1;
        ArrayList<BanHangCode> list = new ConnectionMySQL_SanPhamDaBan().getListBanHang();
        for(int i=0;i<list.size();i++){
            BanHangCode banHang = list.get(i) ;
            if(max < banHang.getLanBan())
                max = banHang.getLanBan();
        }
        return max;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabelAnhSP;
    public javax.swing.JLabel jLabelGiaBan;
    public javax.swing.JLabel jLabelLoaiHang;
    public javax.swing.JLabel jLabelMaMatHang;
    public javax.swing.JLabel jLabelSoLuongBan;
    public javax.swing.JLabel jLabelThanhTien;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
