/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GiaoDienChinh.JPanel;

/**
 *
 * @author Admin
 */
public class ThoiGianBanJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ThoiGianBanJPanel
     */
    public ThoiGianBanJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelMaSanPham = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelThanhTien = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelLoaiHang = new javax.swing.JLabel();
        jLabelSoLuongBan = new javax.swing.JLabel();
        jLabelTheKhachHang = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelGiaBan = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelThoiGianBan = new javax.swing.JLabel();
        jLabelTienBan = new javax.swing.JLabel();
        jLabelGiamGia = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Mã sản phẩm :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, 40));

        jLabelMaSanPham.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelMaSanPham.setForeground(new java.awt.Color(0, 102, 255));
        jLabelMaSanPham.setText("AKL1");
        add(jLabelMaSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 70, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Thành tiền :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 120, 40));

        jLabelThanhTien.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelThanhTien.setForeground(new java.awt.Color(0, 102, 255));
        jLabelThanhTien.setText("10,000,000 VNĐ");
        add(jLabelThanhTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 210, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Loại hàng :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Thẻ khách hàng :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Giá bán          :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 130, 40));

        jLabelLoaiHang.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelLoaiHang.setForeground(new java.awt.Color(0, 102, 255));
        jLabelLoaiHang.setText("Áo khoát len");
        add(jLabelLoaiHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 140, 40));

        jLabelSoLuongBan.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelSoLuongBan.setForeground(new java.awt.Color(0, 102, 255));
        jLabelSoLuongBan.setText("10 Cái");
        add(jLabelSoLuongBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 140, 40));

        jLabelTheKhachHang.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelTheKhachHang.setForeground(new java.awt.Color(0, 102, 255));
        jLabelTheKhachHang.setText("Bạch kim");
        add(jLabelTheKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 140, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("SL Bán           :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 130, 40));

        jLabelGiaBan.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelGiaBan.setForeground(new java.awt.Color(0, 102, 255));
        jLabelGiaBan.setText("150,000 VNĐ");
        add(jLabelGiaBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 140, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Thời gian bán :");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 130, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Giảm giá    :");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 120, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Tiền Bán    :");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 120, 40));

        jLabelThoiGianBan.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelThoiGianBan.setForeground(new java.awt.Color(0, 102, 255));
        jLabelThoiGianBan.setText("11:11:11 20/05/2020");
        add(jLabelThoiGianBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 210, 40));

        jLabelTienBan.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelTienBan.setForeground(new java.awt.Color(0, 102, 255));
        jLabelTienBan.setText("10,000,000 VNĐ");
        add(jLabelTienBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 210, 40));

        jLabelGiamGia.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabelGiamGia.setForeground(new java.awt.Color(0, 102, 255));
        jLabelGiamGia.setText("7%");
        add(jLabelGiamGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, 70, 40));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOpaque(true);
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 950, 10));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ThongKe/nenKhoHang.jpeg"))); // NOI18N
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 140));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabelGiaBan;
    public javax.swing.JLabel jLabelGiamGia;
    public javax.swing.JLabel jLabelLoaiHang;
    public javax.swing.JLabel jLabelMaSanPham;
    public javax.swing.JLabel jLabelSoLuongBan;
    public javax.swing.JLabel jLabelThanhTien;
    public javax.swing.JLabel jLabelTheKhachHang;
    public javax.swing.JLabel jLabelThoiGianBan;
    public javax.swing.JLabel jLabelTienBan;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
