/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GiaoDienChinh.JPanel.ThongKe;

/**
 *
 * @author Admin
 */
public class GiaCaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form KhoHangJPanel
     */
    public GiaCaJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabelGiaBan = new javax.swing.JLabel();
        jLabelMaSanPham = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelLoaiHang = new javax.swing.JLabel();
        jLabelGiaNhap = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel10.setText("Nam");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelGiaBan.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabelGiaBan.setForeground(new java.awt.Color(0, 102, 255));
        jLabelGiaBan.setText("120,000 VNĐ");
        add(jLabelGiaBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 170, 50));

        jLabelMaSanPham.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabelMaSanPham.setForeground(new java.awt.Color(0, 102, 255));
        jLabelMaSanPham.setText("KQC4");
        add(jLabelMaSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 90, 50));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOpaque(true);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 940, 10));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Loại hàng : ");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 50));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Giá Nhập :");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 90, 50));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Giá Bán :");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 90, 50));

        jLabelLoaiHang.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabelLoaiHang.setForeground(new java.awt.Color(0, 102, 255));
        jLabelLoaiHang.setText("Khăn quàng cổ");
        add(jLabelLoaiHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 150, 50));

        jLabelGiaNhap.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabelGiaNhap.setForeground(new java.awt.Color(0, 102, 255));
        jLabelGiaNhap.setText("120,000 VNĐ");
        add(jLabelGiaNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 150, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ThongKe/nenKhoHang.jpeg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelGiaBan;
    public javax.swing.JLabel jLabelGiaNhap;
    public javax.swing.JLabel jLabelLoaiHang;
    public javax.swing.JLabel jLabelMaSanPham;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
