/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GiaoDienChinh.JPanel.ThongKe;

/**
 *
 * @author Admin
 */
public class KhoHangJPanel extends javax.swing.JPanel {

    /**
     * Creates new form KhoHangJPanel
     */
    public KhoHangJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelMau = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelLoaiHang = new javax.swing.JLabel();
        jLabelGioiTinh = new javax.swing.JLabel();
        jLabelSize = new javax.swing.JLabel();
        jLabelThoiGianNhap = new javax.swing.JLabel();
        jLabelMaSanPham = new javax.swing.JLabel();
        jLabelNoiSanXuat = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel10.setText("Nam");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Thời gian nhập :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 150, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Size :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 60, 40));

        jLabelMau.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabelMau.setForeground(new java.awt.Color(0, 102, 255));
        jLabelMau.setText("Xanh dương");
        add(jLabelMau, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 150, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Giới tính :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 110, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Mã Sản Phẩm :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 140, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Màu :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 110, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Nơi Sản Xuất :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 130, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Loại hàng : ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 110, 40));

        jLabelLoaiHang.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabelLoaiHang.setForeground(new java.awt.Color(0, 102, 255));
        jLabelLoaiHang.setText("Khăn quàng cổ");
        add(jLabelLoaiHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 150, 40));

        jLabelGioiTinh.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabelGioiTinh.setForeground(new java.awt.Color(0, 102, 255));
        jLabelGioiTinh.setText("Nam");
        add(jLabelGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 90, 40));

        jLabelSize.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabelSize.setForeground(new java.awt.Color(0, 102, 255));
        jLabelSize.setText("XXL");
        add(jLabelSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 130, 40));

        jLabelThoiGianNhap.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabelThoiGianNhap.setForeground(new java.awt.Color(0, 102, 255));
        jLabelThoiGianNhap.setText("11:12:12 24/1/2021");
        add(jLabelThoiGianNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, 200, 40));

        jLabelMaSanPham.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabelMaSanPham.setForeground(new java.awt.Color(0, 51, 255));
        jLabelMaSanPham.setText("KQC4");
        add(jLabelMaSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 90, 40));

        jLabelNoiSanXuat.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabelNoiSanXuat.setForeground(new java.awt.Color(0, 102, 255));
        jLabelNoiSanXuat.setText("Việt Nam");
        add(jLabelNoiSanXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 140, 40));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOpaque(true);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 940, 10));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ThongKe/nenKhoHang.jpeg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 90));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabelGioiTinh;
    public javax.swing.JLabel jLabelLoaiHang;
    public javax.swing.JLabel jLabelMaSanPham;
    public javax.swing.JLabel jLabelMau;
    public javax.swing.JLabel jLabelNoiSanXuat;
    public javax.swing.JLabel jLabelSize;
    public javax.swing.JLabel jLabelThoiGianNhap;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
