/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GiaoDienChinh.JPanel.ThongKe;

/**
 *
 * @author Admin
 */
public class TienLoiJPanel extends javax.swing.JPanel {

    /**
     * Creates new form KhoHangJPanel
     */
    public TienLoiJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabelTienLoi = new javax.swing.JLabel();
        jLabelMaSanPham = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelLoaiHang = new javax.swing.JLabel();
        jLabelSLNhap = new javax.swing.JLabel();
        jLabelGiaNhap = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelSLBan = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabelGiaBan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel10.setText("Nam");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTienLoi.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabelTienLoi.setForeground(new java.awt.Color(0, 102, 255));
        jLabelTienLoi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTienLoi.setText("100,000,000 VNĐ");
        add(jLabelTienLoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 230, 50));

        jLabelMaSanPham.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabelMaSanPham.setForeground(new java.awt.Color(0, 102, 255));
        jLabelMaSanPham.setText("KQC4");
        add(jLabelMaSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 60, 50));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOpaque(true);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 940, 10));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Mã Sản Phẩm : ");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, 50));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("SL Nhập :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 80, 50));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText(" Giá Nhập :");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 100, 50));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Tiền Lời :");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 130, 40));

        jLabelLoaiHang.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabelLoaiHang.setForeground(new java.awt.Color(0, 102, 255));
        jLabelLoaiHang.setText("Khăn quàng cổ");
        add(jLabelLoaiHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 160, 50));

        jLabelSLNhap.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabelSLNhap.setForeground(new java.awt.Color(0, 102, 255));
        jLabelSLNhap.setText("1000 Cái");
        add(jLabelSLNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 110, 50));

        jLabelGiaNhap.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabelGiaNhap.setForeground(new java.awt.Color(0, 102, 255));
        jLabelGiaNhap.setText("100,000 VNĐ");
        add(jLabelGiaNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 150, 50));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Loại hàng : ");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 50));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("SL Bán   :");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 80, 50));

        jLabelSLBan.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabelSLBan.setForeground(new java.awt.Color(0, 102, 255));
        jLabelSLBan.setText("1000 Cái");
        add(jLabelSLBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 110, 50));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText(" Giá Bán   :");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 100, 50));

        jLabelGiaBan.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabelGiaBan.setForeground(new java.awt.Color(0, 102, 255));
        jLabelGiaBan.setText("100,000 VNĐ");
        add(jLabelGiaBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 150, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ThongKe/nenKhoHang.jpeg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 90));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelGiaBan;
    public javax.swing.JLabel jLabelGiaNhap;
    public javax.swing.JLabel jLabelLoaiHang;
    public javax.swing.JLabel jLabelMaSanPham;
    public javax.swing.JLabel jLabelSLBan;
    public javax.swing.JLabel jLabelSLNhap;
    public javax.swing.JLabel jLabelTienLoi;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
